/**
 * Generador PDF — Informe 0: Mercado Inmobiliario Equipetrol (Macro)
 * Colores: Simon Brand (Negro #0a0a0a, Crema #f8f6f3, Oro #c9a959)
 * Datos limpios: excluye duplicados, parqueos/bauleras, >300d (730 preventa), multiproyecto
 *
 * Ejecutar: node scripts/generate-equipetrol-macro-report.jsx
 */

const React = require('react');
const { Document, Page, Text, View, StyleSheet, renderToFile } = require('@react-pdf/renderer');
const path = require('path');
const fs = require('fs');

// ─── Brand Colors ───
const C = {
  negro: '#0a0a0a', crema: '#f8f6f3', oro: '#c9a959', oroClaro: '#d4bc7a',
  blanco: '#ffffff', gris: '#666666', grisMedio: '#999999', grisClaro: '#e5e5e5',
  rojo: '#c94040', verde: '#4a9960', azul: '#4a7099',
};

// ─── Styles ───
const s = StyleSheet.create({
  pageCover: { backgroundColor: C.negro, padding: 60, justifyContent: 'center', alignItems: 'center' },
  pageCrema: { backgroundColor: C.crema, padding: 40, paddingBottom: 50, fontSize: 9, fontFamily: 'Helvetica', color: C.negro },
  pageNegro: { backgroundColor: C.negro, padding: 40, paddingBottom: 50, fontSize: 9, fontFamily: 'Helvetica', color: C.blanco },
  coverLabel: { color: C.oro, fontSize: 8, letterSpacing: 4, textTransform: 'uppercase', marginBottom: 24 },
  coverTitle: { color: C.blanco, fontSize: 32, fontFamily: 'Helvetica-Bold', textAlign: 'center', marginBottom: 8 },
  coverSubtitle: { color: C.oro, fontSize: 18, textAlign: 'center', marginBottom: 40, fontStyle: 'italic' },
  coverMeta: { color: '#ffffff99', fontSize: 9, textAlign: 'center', marginBottom: 4 },
  coverLine: { width: 40, height: 1, backgroundColor: C.oro, marginVertical: 20 },
  sectionLabel: { color: C.oro, fontSize: 7, letterSpacing: 3, textTransform: 'uppercase', marginBottom: 6 },
  sectionTitle: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 12 },
  sectionTitleBlanco: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 12, color: C.blanco },
  sectionSubtitle: { fontSize: 11, color: C.gris, marginBottom: 16, lineHeight: 1.5 },
  sectionSubtitleBlanco: { fontSize: 11, color: '#ffffffaa', marginBottom: 16, lineHeight: 1.5 },
  body: { fontSize: 9, lineHeight: 1.6, marginBottom: 8, color: C.gris },
  bodyBlanco: { fontSize: 9, lineHeight: 1.6, marginBottom: 8, color: '#ffffffcc' },
  bold: { fontFamily: 'Helvetica-Bold' },
  oro: { color: C.oro },
  rojo: { color: C.rojo },
  verde: { color: C.verde },
  table: { marginBottom: 16 },
  tableHeader: { flexDirection: 'row', backgroundColor: C.negro, paddingVertical: 6, paddingHorizontal: 8 },
  tableHeaderNegro: { flexDirection: 'row', backgroundColor: '#ffffff15', paddingVertical: 6, paddingHorizontal: 8 },
  tableRow: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, borderBottomWidth: 0.5, borderBottomColor: '#00000010' },
  tableRowNegro: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, borderBottomWidth: 0.5, borderBottomColor: '#ffffff10' },
  tableRowAlt: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, backgroundColor: '#00000005', borderBottomWidth: 0.5, borderBottomColor: '#00000010' },
  tableRowHighlight: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, backgroundColor: '#c9a95915', borderBottomWidth: 0.5, borderBottomColor: '#c9a95930' },
  tableRowHighlightNegro: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, backgroundColor: '#c9a95920', borderBottomWidth: 0.5, borderBottomColor: '#c9a95940' },
  th: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.blanco, textTransform: 'uppercase', letterSpacing: 1 },
  thNegro: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.oro, textTransform: 'uppercase', letterSpacing: 1 },
  td: { fontSize: 8, color: C.negro },
  tdNegro: { fontSize: 8, color: '#ffffffdd' },
  tdBold: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: C.negro },
  tdOro: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: C.oro },
  kpiRow: { flexDirection: 'row', marginBottom: 16, gap: 12 },
  kpiBox: { flex: 1, backgroundColor: C.negro, padding: 14, alignItems: 'center' },
  kpiBoxCrema: { flex: 1, backgroundColor: C.crema, padding: 14, alignItems: 'center', borderWidth: 0.5, borderColor: '#00000015' },
  kpiValue: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: C.oro, marginBottom: 4 },
  kpiValueNegro: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: C.negro, marginBottom: 4 },
  kpiLabel: { fontSize: 7, color: '#ffffff88', textTransform: 'uppercase', letterSpacing: 2, textAlign: 'center' },
  kpiLabelNegro: { fontSize: 7, color: C.gris, textTransform: 'uppercase', letterSpacing: 2, textAlign: 'center' },
  callout: { backgroundColor: '#c9a95912', borderLeftWidth: 2, borderLeftColor: C.oro, padding: 12, marginBottom: 16 },
  calloutNegro: { backgroundColor: '#c9a95915', borderLeftWidth: 2, borderLeftColor: C.oro, padding: 12, marginBottom: 16 },
  calloutRojo: { backgroundColor: '#c9404012', borderLeftWidth: 2, borderLeftColor: C.rojo, padding: 12, marginBottom: 16 },
  calloutVerde: { backgroundColor: '#4a996012', borderLeftWidth: 2, borderLeftColor: C.verde, padding: 12, marginBottom: 16 },
  footer: { position: 'absolute', bottom: 20, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 7, color: '#ffffff55' },
  footerTextNegro: { fontSize: 7, color: '#00000044' },
  divider: { height: 0.5, backgroundColor: '#00000015', marginVertical: 12 },
  dividerBlanco: { height: 0.5, backgroundColor: '#ffffff20', marginVertical: 12 },
  smallNote: { fontSize: 7, color: C.grisMedio, lineHeight: 1.4, marginTop: 4 },
  smallNoteBlanco: { fontSize: 7, color: '#ffffff66', lineHeight: 1.4, marginTop: 4 },
});

const Footer = ({ num, total, dark }) => (
  React.createElement(View, { style: s.footer },
    React.createElement(Text, { style: dark ? s.footerText : s.footerTextNegro }, 'SICI Intelligence'),
    React.createElement(Text, { style: dark ? s.footerText : s.footerTextNegro }, `${num} / ${total}`)
  )
);

const TOTAL_PAGES = 9;

// ═══════════════════════════════════════════
// INFORME 0: MERCADO EQUIPETROL MACRO
// Datos limpios al 18 Feb 2026
// ═══════════════════════════════════════════
const EquipetrolReport = () => React.createElement(Document, {},

  // ─── P1: Cover ───
  React.createElement(Page, { size: 'A4', style: s.pageCover },
    React.createElement(Text, { style: s.coverLabel }, 'INFORME DE INTELIGENCIA DE MERCADO'),
    React.createElement(Text, { style: s.coverTitle }, 'EQUIPETROL'),
    React.createElement(Text, { style: s.coverSubtitle }, 'Panorama completo del mercado inmobiliario'),
    React.createElement(View, { style: s.coverLine }),
    React.createElement(Text, { style: s.coverMeta }, '5 microzonas — 222 unidades activas — 48 absorbidas en 30 dias'),
    React.createElement(Text, { style: s.coverMeta }, 'Elaborado con datos del Sistema SICI'),
    React.createElement(Text, { style: s.coverMeta }, '18 de febrero de 2026'),
    React.createElement(Text, { style: { ...s.coverMeta, marginTop: 20 } }, 'Fuentes: Century 21 Bolivia, Remax Bolivia, Binance P2P'),
    React.createElement(Text, { style: s.coverMeta }, 'Precios en USD (TC oficial Bs 6.96). Fuente TC paralelo: Binance P2P'),
  ),

  // ─── P2: Resumen Ejecutivo ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'RESUMEN EJECUTIVO'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Equipetrol en 30 segundos'),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '222'),
        React.createElement(Text, { style: s.kpiLabel }, 'VENTA ACTIVAS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '48'),
        React.createElement(Text, { style: s.kpiLabel }, 'ABSORBIDAS 30D'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '17.8%'),
        React.createElement(Text, { style: s.kpiLabel }, 'TASA ABSORCION'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '4.6'),
        React.createElement(Text, { style: s.kpiLabel }, 'MESES INVENTARIO'),
      ),
    ),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '$2,071'),
        React.createElement(Text, { style: s.kpiLabel }, 'MEDIANA $/M2'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '$140K'),
        React.createElement(Text, { style: s.kpiLabel }, 'TICKET MEDIANO'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '95'),
        React.createElement(Text, { style: s.kpiLabel }, 'ALQUILERES'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '5.5-6.9%'),
        React.createElement(Text, { style: s.kpiLabel }, 'ROI BRUTO'),
      ),
    ),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Mercado activo: ~1.6 unidades absorbidas por dia.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Equipetrol no esta parado. 48 absorbidas en 30 dias con inventario limpio de 222 unidades.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Dos motores: V. Brigida (25%) y Eq. Centro (22%).'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Juntos suman el 83% de las absorciones. V. Brigida es la mas rapida, Eq. Centro mueve mas volumen.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '1D es el producto mas liquido (22.2%). 2D es el mas lento (9.9%).'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Para volumen de venta, priorizar 1D. Los 2D requieren 9 meses de inventario para vaciarse.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Sirari: premium + iliquido en portales.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Solo 4.8% absorcion visible. Las ventas ocurren directo con desarrolladoras, fuera de portales.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'ROI bruto: estudios lideran (6.9%). Sirari y Eq. Oeste tienen las rentas 2D mas altas.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Para inversores, el sweet spot es Sirari 2D: renta $1,124/mes, ROI 6.6%.'),
    ),
    React.createElement(Footer, { num: 2, total: TOTAL_PAGES, dark: true }),
  ),

  // ─── P3: Metodologia + KPIs ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'METODOLOGIA'),
    React.createElement(Text, { style: s.sectionTitle }, 'Que mide este informe'),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: s.body },
        'Este informe analiza 222 propiedades de venta activas y 95 alquileres en toda la macro-zona de Equipetrol. Los datos provienen del scraping automatizado diario de Century 21 Bolivia y Remax Bolivia. Los precios estan normalizados a USD al tipo de cambio oficial (Bs 6.96/USD). Los anuncios publicados "al paralelo" se convierten a USD oficial: precio x TC Binance (9.26) / 6.96.'),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, 'Filtros de calidad aplicados:'),
      React.createElement(Text, { style: s.body }, 'Se excluyen duplicados (duplicado_de), parqueos/bauleras/garajes, multiproyectos, unidades < 20 m2, y propiedades con mas de 300 dias en mercado (730 para preventa). Estos filtros aseguran que cada unidad contada es real y vigente.'),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, 'Absorcion = propiedades que desaparecieron de portales en los ultimos 30 dias.'),
      React.createElement(Text, { style: s.body }, 'No equivale a "vendidas" — puede incluir: venta cerrada, baja temporal, cambio de agente, expiracion de anuncio. Pero es el mejor proxy disponible de velocidad de mercado.'),
    ),
    React.createElement(View, { style: s.divider }),
    React.createElement(Text, { style: s.sectionLabel }, 'EQUIPETROL EN NUMEROS'),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '222'),
        React.createElement(Text, { style: s.kpiLabel }, 'VENTA ACTIVAS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '48'),
        React.createElement(Text, { style: s.kpiLabel }, 'ABSORBIDAS 30D'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '17.8%'),
        React.createElement(Text, { style: s.kpiLabel }, 'TASA ABSORCION'),
      ),
    ),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '$2,078'),
        React.createElement(Text, { style: s.kpiLabel }, 'USD/M2 PROMEDIO'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '95'),
        React.createElement(Text, { style: s.kpiLabel }, 'ALQUILERES ACTIVOS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '5'),
        React.createElement(Text, { style: s.kpiLabel }, 'MICROZONAS'),
      ),
    ),
    React.createElement(Footer, { num: 3, total: TOTAL_PAGES }),
  ),

  // ─── P4: Microzonas ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'MICROZONAS'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Cinco barrios, un mercado'),
    React.createElement(Text, { style: s.sectionSubtitleBlanco }, 'Todas las microzonas estan a menos de 1 km entre si. El comprador las considera como un solo mercado.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '22%' } }, 'MICROZONA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'VENTA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '11%' } }, 'ABSORB.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'TASA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '12%' } }, '$/M2'),
        React.createElement(Text, { style: { ...s.thNegro, width: '12%' } }, 'TICKET'),
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'ALQ.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '13%' } }, 'PERFIL'),
      ),
      // Eq Centro — motor del mercado
      React.createElement(View, { style: s.tableRowHighlightNegro },
        React.createElement(Text, { style: { ...s.tdOro, width: '22%' } }, 'Eq. Centro'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '99'),
        React.createElement(Text, { style: { ...s.tdOro, width: '11%' } }, '28'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '22.0%'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '$2,138'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '$136K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '36'),
        React.createElement(Text, { style: { ...s.tdOro, width: '13%' } }, 'Motor'),
      ),
      // Villa Brigida — segundo motor, precio mas bajo
      React.createElement(View, { style: s.tableRowHighlightNegro },
        React.createElement(Text, { style: { ...s.tdOro, width: '22%' } }, 'V. Brigida'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '36'),
        React.createElement(Text, { style: { ...s.tdOro, width: '11%' } }, '12'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '10%', fontSize: 8 } }, '25.0%'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '$1,862'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '$121K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '13'),
        React.createElement(Text, { style: { ...s.tdOro, width: '13%' } }, 'Emergente'),
      ),
      // Sirari — premium, lenta en portales
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, 'Sirari'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '40'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '11%' } }, '2'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '10%', fontSize: 8 } }, '4.8%'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '$2,118'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '$153K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '9'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '13%' } }, 'Premium'),
      ),
      // Eq Oeste
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, 'Eq. Oeste'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '25'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '11%' } }, '3'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '10.7%'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '$2,208'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '$150K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '10'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '13%' } }, 'Mixto'),
      ),
      // Eq Norte
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, 'Eq. Norte'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '22'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '11%' } }, '3'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '12.0%'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '$2,442'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '$155K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '27'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '13%' } }, 'Financiero'),
      ),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, 'Distancias reales entre centroides (GPS):'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Sirari <> Eq. Norte: 584-710m | Sirari <> Eq. Centro: 760m | Sirari <> Eq. Oeste: 1,022m | Sirari <> V. Brigida: 1,030m'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'V. Brigida lidera absorcion (25%) — el mercado mas rapido de Equipetrol.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Eq. Centro le sigue con 22%. Sirari es la mas lenta en portales (4.8%) — zona premium donde las ventas se hacen mas directo (desarrolladoras), no por portales. Eq. Norte sorprende con 27 alquileres activos (mas que V. Brigida con 13) pese a tener solo 22 ventas.'),
    ),
    React.createElement(Footer, { num: 4, total: TOTAL_PAGES, dark: true }),
  ),

  // ─── P5: Precios por Tipologia (Macro) ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'PRECIOS DE VENTA'),
    React.createElement(Text, { style: s.sectionTitle }, 'Mercado por tipologia — todo Equipetrol'),
    React.createElement(Text, { style: s.sectionSubtitle }, '222 unidades activas (datos limpios). Al 18 Feb 2026. Precios en USD (TC oficial Bs 6.96).'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'TIPO'),
        React.createElement(Text, { style: { ...s.th, width: '10%' } }, 'ACTIVAS'),
        React.createElement(Text, { style: { ...s.th, width: '10%' } }, 'ABSORB.'),
        React.createElement(Text, { style: { ...s.th, width: '10%' } }, 'TASA'),
        React.createElement(Text, { style: { ...s.th, width: '12%' } }, '$/M2 MED.'),
        React.createElement(Text, { style: { ...s.th, width: '11%' } }, 'P25'),
        React.createElement(Text, { style: { ...s.th, width: '12%' } }, 'MEDIANA'),
        React.createElement(Text, { style: { ...s.th, width: '11%' } }, 'P75'),
        React.createElement(Text, { style: { ...s.th, width: '10%' } }, 'AREA'),
      ),
      // Estudio
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, 'Estudio'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '28'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '9'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '10%', fontSize: 8 } }, '24.3%'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$2,369'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$73K'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$87K'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$102K'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '38 m2'),
      ),
      // 1D
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '1 Dorm'),
        React.createElement(Text, { style: { ...s.tdBold, width: '10%' } }, '91'),
        React.createElement(Text, { style: { ...s.tdBold, width: '10%' } }, '26'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '10%', fontSize: 8 } }, '22.2%'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$2,147'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$94K'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$107K'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$145K'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '55 m2'),
      ),
      // 2D
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '2 Dorms'),
        React.createElement(Text, { style: { ...s.tdBold, width: '10%' } }, '80'),
        React.createElement(Text, { style: { ...s.tdBold, width: '10%' } }, '9'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '10.1%'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$2,056'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$155K'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$189K'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$233K'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '98 m2'),
      ),
      // 3D
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '3 Dorms'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '19'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '4'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '10%', fontSize: 8 } }, '17.4%'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$1,959'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$275K'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$348K'),
        React.createElement(Text, { style: { ...s.td, width: '11%' } }, '$477K'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '191 m2'),
      ),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, 'Estudios y 1D lideran absorcion (22-24%). El 2D es el mas lento (10.1%) y el mas disputado.'),
      React.createElement(Text, { style: s.body }, 'El segmento 2D tiene 80 unidades activas compitiendo, 9 absorbidas en 30 dias — ~9 meses de inventario. Los 1D son el segmento mas liquido: 91 activas con 22.2% de absorcion (~3.5 meses de inventario). El 3D tiene buena tasa (17.4%) pero muestra chica (19 unidades).'),
    ),
    React.createElement(View, { style: s.divider }),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, 'Rango de precios $/m2: los estudios son los mas caros por metro cuadrado.'),
      React.createElement(Text, { style: s.body }, 'Estudio $2,369/m2 > 1D $2,147 > 2D $2,056 > 3D $1,959. Pagas una prima por area pequenha (38 m2 promedio). El ticket de entrada sube con los dormitorios: $87K (estudio) a $348K (3D mediana).'),
    ),
    React.createElement(Footer, { num: 5, total: TOTAL_PAGES }),
  ),

  // ─── P6: Absorcion por Microzona x Tipologia ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'MAPA DE CALOR'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Absorcion por microzona y tipologia'),
    React.createElement(Text, { style: s.sectionSubtitleBlanco }, 'Donde se mueve cada tipo de departamento. Tasa = absorbidas / (activas + absorbidas) ultimos 30 dias.'),
    // 1 Dormitorio
    React.createElement(Text, { style: { ...s.sectionLabel, marginTop: 4 } }, '1 DORMITORIO — 91 activas, 26 absorbidas'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '25%' } }, 'MICROZONA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'ACTIVAS'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'ABSORB.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'TASA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, '$/M2'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'RENTA'),
      ),
      ...[
        ['Eq. Centro', '40', '18', '31.0%', '$2,159', '$538', true],
        ['Sirari', '19', '2', '9.5%', '$2,098', '$647', false],
        ['V. Brigida', '13', '3', '18.8%', '$2,017', '$470', false],
        ['Eq. Oeste', '11', '1', '8.3%', '$2,216', '$643', false],
        ['Eq. Norte', '8', '2', '20.0%', '$2,323', '$821', false],
      ].map(([zona, act, abs, tasa, m2, renta, highlight], i) =>
        React.createElement(View, { key: `1d-${i}`, style: highlight ? s.tableRowHighlightNegro : s.tableRowNegro },
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '25%' } }, zona),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, act),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, abs),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%', fontFamily: 'Helvetica-Bold' } }, tasa),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, m2),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, renta),
        )
      ),
    ),
    // 2 Dormitorios
    React.createElement(Text, { style: { ...s.sectionLabel, marginTop: 8 } }, '2 DORMITORIOS — 80 activas, 9 absorbidas'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '25%' } }, 'MICROZONA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'ACTIVAS'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'ABSORB.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'TASA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, '$/M2'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'RENTA'),
      ),
      ...[
        ['Eq. Centro', '39', '3', '7.1%', '$2,060', '$929', false],
        ['V. Brigida', '14', '4', '22.2%', '$1,755', '$845', true],
        ['Eq. Oeste', '10', '1', '9.1%', '$2,068', '$1,106', false],
        ['Eq. Norte', '9', '1', '10.0%', '$2,515', '$1,004', false],
        ['Sirari', '8', '0', '0.0%', '$2,035', '$1,124', false],
      ].map(([zona, act, abs, tasa, m2, renta, highlight], i) =>
        React.createElement(View, { key: `2d-${i}`, style: highlight ? s.tableRowHighlightNegro : s.tableRowNegro },
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '25%' } }, zona),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, act),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, abs),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%', fontFamily: 'Helvetica-Bold' } }, tasa),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, m2),
          React.createElement(Text, { style: { ...(highlight ? s.tdOro : s.tdNegro), width: '15%' } }, renta),
        )
      ),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '1D: Eq. Centro absorbe 31% — casi 1 de cada 3 unidades en 30 dias.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'El 1D es el producto estrella de Eq. Centro (40 activas, 18 absorbidas). Eq. Norte renta alto ($821/mes) con pocos 1D — nicho rentable. V. Brigida muestra 18.8%, solida.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '2D: V. Brigida lidera (22.2%), Sirari en cero (0%).'),
      React.createElement(Text, { style: s.bodyBlanco }, 'V. Brigida tiene el 2D mas barato ($1,755/m2) y la absorcion mas alta. Sirari tiene el 2D mas caro y cero absorciones en portales — las ventas premium se hacen directo con desarrolladoras, fuera de portales.'),
    ),
    React.createElement(Footer, { num: 6, total: TOTAL_PAGES, dark: true }),
  ),

  // ─── P7: Renta y ROI ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'RENTA E INVERSION'),
    React.createElement(Text, { style: s.sectionTitle }, 'ROI bruto por tipologia — todo Equipetrol'),
    React.createElement(Text, { style: s.sectionSubtitle }, '95 alquileres activos rastreados (C21 + Remax). Renta en USD (TC oficial). ROI = (renta mediana x 12) / ticket mediana venta.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'TIPO'),
        React.createElement(Text, { style: { ...s.th, width: '10%' } }, 'ALQ.'),
        React.createElement(Text, { style: { ...s.th, width: '12%' } }, 'RENTA MED.'),
        React.createElement(Text, { style: { ...s.th, width: '10%' } }, 'P25'),
        React.createElement(Text, { style: { ...s.th, width: '10%' } }, 'P75'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'TICKET VENTA'),
        React.createElement(Text, { style: { ...s.th, width: '12%' } }, 'ROI BRUTO'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'ANOS RETORNO'),
      ),
      // Estudio: ROI = ($503 * 12) / $87K = 6.94%
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, 'Estudio'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '13'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$503'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$460'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$546'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$87K'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '12%', fontSize: 8 } }, '6.94%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '14.4 anhos'),
      ),
      // 1D: ROI = ($546 * 12) / $107K = 6.12%
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '1 Dorm'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '44'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$546'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$471'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$756'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$107K'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '12%', fontSize: 8 } }, '6.12%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '16.3 anhos'),
      ),
      // 2D: ROI = ($862 * 12) / $189K = 5.47%
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '2 Dorms'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '31'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$862'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$797'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$1,149'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$189K'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '5.47%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '18.3 anhos'),
      ),
      // 3D: ROI = ($1,652 * 12) / $348K = 5.70%
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '3 Dorms'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '5'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$1,652'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$1,437'),
        React.createElement(Text, { style: { ...s.td, width: '10%' } }, '$1,796'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$348K'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '5.70%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '17.5 anhos'),
      ),
    ),
    React.createElement(Text, { style: s.smallNote }, 'ROI bruto = (renta mediana x 12) / ticket mediana venta. No descuenta vacancia, mantenimiento, comisiones ni impuestos. Muestra alquiler: 95 activas (C21 + Remax).'),
    React.createElement(View, { style: s.divider }),
    React.createElement(Text, { style: s.sectionLabel }, 'RENTA POR MICROZONA — 2 DORMITORIOS'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '25%' } }, 'MICROZONA'),
        React.createElement(Text, { style: { ...s.th, width: '15%' } }, 'MUESTRA'),
        React.createElement(Text, { style: { ...s.th, width: '20%' } }, 'RENTA PROM.'),
        React.createElement(Text, { style: { ...s.th, width: '20%' } }, '$/M2 VENTA'),
        React.createElement(Text, { style: { ...s.th, width: '20%' } }, 'ROI EST.'),
      ),
      ...[
        ['Sirari', '3', '$1,124', '$2,035', '6.63%'],
        ['Eq. Oeste', '4', '$1,106', '$2,068', '6.42%'],
        ['Eq. Norte', '4', '$1,004', '$2,515', '4.79%'],
        ['Eq. Centro', '16', '$929', '$2,060', '5.41%'],
        ['V. Brigida', '4', '$845', '$1,755', '5.78%'],
      ].map(([zona, n, renta, m2, roi], i) =>
        React.createElement(View, { key: `r-${i}`, style: i % 2 === 0 ? s.tableRow : s.tableRowAlt },
          React.createElement(Text, { style: { ...s.tdBold, width: '25%' } }, zona),
          React.createElement(Text, { style: { ...s.td, width: '15%' } }, n),
          React.createElement(Text, { style: { ...s.td, width: '20%' } }, renta),
          React.createElement(Text, { style: { ...s.td, width: '20%' } }, m2),
          React.createElement(Text, { style: { ...s.tdBold, width: '20%' } }, roi),
        )
      ),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, 'Sirari y Eq. Oeste lideran ROI en 2D (6.4-6.6%) por rentas altas. Eq. Norte tiene la renta mas baja vs precio alto — ROI diluido.'),
    ),
    React.createElement(Text, { style: s.smallNote }, 'ROI estimado = (renta promedio x 12) / ($/m2 venta x area promedio 2D 98m2). Las muestras de renta son chicas (3-16); usar como referencia directiva, no como precio exacto.'),
    React.createElement(Footer, { num: 7, total: TOTAL_PAGES }),
  ),

  // ─── P8: Top Proyectos ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'PROYECTOS PRINCIPALES'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Top 15 edificios por inventario activo'),
    React.createElement(Text, { style: s.sectionSubtitleBlanco }, 'Solo proyectos con 4+ unidades activas en portales (C21 + Remax). Datos limpios.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '28%' } }, 'PROYECTO'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'MICROZONA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'UDS'),
        React.createElement(Text, { style: { ...s.thNegro, width: '14%' } }, '$/M2'),
        React.createElement(Text, { style: { ...s.thNegro, width: '12%' } }, 'AREA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '20%' } }, 'TIPOLOGIAS'),
      ),
      ...[
        ['Sky Eclipse', 'Eq. Oeste', '12', '$2,478', '75m2', '0-2D', false],
        ['Atrium', 'Eq. Centro', '11', '$2,090', '78m2', '1-2D', false],
        ['T-VEINTICINCO', 'Eq. Centro', '9', '$1,894', '117m2', '2D', false],
        ['Las Dalias', 'Sirari', '9', '$2,205', '65m2', '1-2D', false],
        ['HH Once', 'Eq. Centro', '8', '$1,882', '55m2', '0-1D', false],
        ['SKY EQUINOX', 'Sirari', '6', '$1,736', '75m2', '0-2D', false],
        ['Sky Tower', 'Eq. Centro', '6', '$2,939', '36m2', '0-1D', true],
        ['Sky Level', 'Eq. Centro', '5', '$2,055', '68m2', '1-2D', false],
        ['Sky Moon', 'Eq. Norte', '5', '$2,979', '72m2', '0-2D', true],
        ['ITAJU', 'Sirari', '5', '$2,225', '241m2', '3D', true],
        ['Le Blanc', 'Eq. Norte', '5', '$2,157', '83m2', '1-2D', false],
        ['HH Chuubi', 'Eq. Centro', '5', '$1,600', '74m2', '1-2D', false],
        ['Luxe Tower', 'Eq. Centro', '4', '$2,588', '79m2', '1-2D', true],
        ['Stone 3', 'V. Brigida', '4', '$2,106', '39m2', '0-1D', false],
        ['Aura Residences', 'V. Brigida', '4', '$1,345', '95m2', '2-3D', false],
      ].map(([proy, micro, uds, m2, area, tipos, premium], i) =>
        React.createElement(View, { key: `p-${i}`, style: premium ? s.tableRowHighlightNegro : s.tableRowNegro },
          React.createElement(Text, { style: { ...(premium ? s.tdOro : s.tdNegro), width: '28%', fontFamily: 'Helvetica-Bold' } }, proy),
          React.createElement(Text, { style: { ...(premium ? s.tdOro : s.tdNegro), width: '16%' } }, micro),
          React.createElement(Text, { style: { ...(premium ? s.tdOro : s.tdNegro), width: '10%' } }, uds),
          React.createElement(Text, { style: { ...(premium ? s.tdOro : s.tdNegro), width: '14%' } }, m2),
          React.createElement(Text, { style: { ...(premium ? s.tdOro : s.tdNegro), width: '12%' } }, area),
          React.createElement(Text, { style: { ...(premium ? s.tdOro : s.tdNegro), width: '20%' } }, tipos),
        )
      ),
    ),
    React.createElement(Text, { style: s.smallNoteBlanco }, 'Resaltados en oro: segmento ultra-premium (>$2,200/m2). Sky Tower y Sky Moon son los mas caros del mercado (~$3,000/m2).'),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Sky Eclipse lidera con 12 uds en Eq. Oeste ($2,478/m2) — premium en zona mixta.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Eq. Oeste combina proyectos premium (Sky Eclipse, Lofty Island) con oferta mas accesible. Atrium (11 uds) y T-VEINTICINCO (9 uds, solo 2D) dominan Eq. Centro. Las Dalias es el edificio con mas inventario en Sirari. Aura Residences en V. Brigida tiene el $/m2 mas bajo ($1,345).'),
    ),
    React.createElement(Footer, { num: 8, total: TOTAL_PAGES, dark: true }),
  ),

  // ─── P9: Conclusiones ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'CONCLUSIONES'),
    React.createElement(Text, { style: s.sectionTitle }, 'El mercado Equipetrol: vivo, segmentado, predecible'),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, '1. El mercado se mueve — 48 absorbidas en 30 dias (17.8% global).'),
      React.createElement(Text, { style: s.body }, 'No es un mercado muerto. Equipetrol absorbe ~1.6 unidades por dia. Los estudios y 1D lideran (22-24%), el 2D es mas lento (10.1%), y el 3D muestra buena senhal (17.4% pero muestra chica).'),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, '2. Dos motores: Eq. Centro (28 absorciones) y V. Brigida (12 absorciones).'),
      React.createElement(Text, { style: s.body }, 'Juntos suman el 83% de las absorciones. V. Brigida lidera en tasa (25%) — el mercado mas rapido de Equipetrol, con el ticket mas bajo ($121K mediana). Eq. Centro mueve el mayor volumen (99 activas, 22% absorcion).'),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, '3. Sirari: premium + iliquido en portales = venta directa.'),
      React.createElement(Text, { style: s.body }, 'Solo 2 absorciones en 30 dias en toda Sirari. Pero los desarrolladores de Sirari (Las Dalias, ITAJU, MARE, Giardino) venden directo a su red de compradores. La baja absorcion en portales NO significa baja demanda real — significa que la venta ocurre por otros canales.'),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, '4. El rango de precios es amplio: $1,345 a $2,979/m2.'),
      React.createElement(Text, { style: s.body }, 'V. Brigida y Aura Residences representan el entry-level ($1,345-$1,862/m2). El segmento ultra-premium (Sky Tower, Sky Moon >$2,900/m2) tiene menos rotacion visible pero rentas mas altas. La mediana del mercado esta en ~$2,050/m2 para 2D.'),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, '5. ROI bruto: 5.5% a 6.9% segun tipologia.'),
      React.createElement(Text, { style: s.body }, 'Los estudios lideran (6.9%) por ticket bajo. El 2D rinde 5.5% en promedio, pero sube a 6.4-6.6% en Sirari y Eq. Oeste donde las rentas son mas altas. Para inversores puros, Sirari combina renta alta + apreciacion de capital.'),
    ),
    React.createElement(View, { style: s.divider }),
    React.createElement(View, { style: { flexDirection: 'row', gap: 12 } },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 16 } }, '222 venta'),
        React.createElement(Text, { style: s.kpiLabel }, 'INVENTARIO LIMPIO'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 16 } }, '95 alquiler'),
        React.createElement(Text, { style: s.kpiLabel }, 'DATAPOINTS RENTA'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 16 } }, 'Diario'),
        React.createElement(Text, { style: s.kpiLabel }, 'ACTUALIZACION SICI'),
      ),
    ),
    React.createElement(Text, { style: { ...s.smallNote, marginTop: 12 } }, 'Datos limpios: excluye duplicados, parqueos/bauleras, multiproyectos, unidades < 20m2, y propiedades > 300 dias en mercado (730 preventa). Absorcion de venta limpia desde ~17 Feb 2026.'),
    React.createElement(Footer, { num: 9, total: TOTAL_PAGES }),
  ),
);

// ─── Generate ───
async function generate() {
  const outputDir = path.join(__dirname, '..', 'docs', 'reports');
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const doc = React.createElement(EquipetrolReport);
  const outputPath = path.join(outputDir, 'INFORME_MERCADO_EQUIPETROL_2026-02-18_v3.pdf');

  console.log('Generating Equipetrol Macro Market report (clean data)...');
  await renderToFile(doc, outputPath);
  console.log(`PDF generated: ${outputPath}`);

  const stats = fs.statSync(outputPath);
  console.log(`Size: ${(stats.size / 1024).toFixed(1)} KB`);
}

generate().catch(console.error);
