/**
 * Generador PDF — Informe Giardino + Portfolio Combinado MARE+Giardino
 * Colores: Simon Brand (Negro #0a0a0a, Crema #f8f6f3, Oro #c9a959)
 *
 * Ejecutar: node scripts/generate-giardino-portfolio.jsx
 */

const React = require('react');
const { Document, Page, Text, View, StyleSheet, renderToFile } = require('@react-pdf/renderer');
const path = require('path');
const fs = require('fs');

// ─── Brand Colors ───
const C = {
  negro: '#0a0a0a', crema: '#f8f6f3', oro: '#c9a959', oroClaro: '#d4bc7a',
  blanco: '#ffffff', gris: '#666666', grisMedio: '#999999', grisClaro: '#e5e5e5',
  rojo: '#c94040', verde: '#4a9960', azul: '#4a7099',
};

// ─── Styles ───
const s = StyleSheet.create({
  pageCover: { backgroundColor: C.negro, padding: 60, justifyContent: 'center', alignItems: 'center' },
  pageCrema: { backgroundColor: C.crema, padding: 40, paddingBottom: 50, fontSize: 9, fontFamily: 'Helvetica', color: C.negro },
  pageNegro: { backgroundColor: C.negro, padding: 40, paddingBottom: 50, fontSize: 9, fontFamily: 'Helvetica', color: C.blanco },
  coverLabel: { color: C.oro, fontSize: 8, letterSpacing: 4, textTransform: 'uppercase', marginBottom: 24 },
  coverTitle: { color: C.blanco, fontSize: 32, fontFamily: 'Helvetica-Bold', textAlign: 'center', marginBottom: 8 },
  coverSubtitle: { color: C.oro, fontSize: 18, textAlign: 'center', marginBottom: 40, fontStyle: 'italic' },
  coverMeta: { color: '#ffffff99', fontSize: 9, textAlign: 'center', marginBottom: 4 },
  coverLine: { width: 40, height: 1, backgroundColor: C.oro, marginVertical: 20 },
  sectionLabel: { color: C.oro, fontSize: 7, letterSpacing: 3, textTransform: 'uppercase', marginBottom: 6 },
  sectionTitle: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 12 },
  sectionTitleBlanco: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 12, color: C.blanco },
  sectionSubtitle: { fontSize: 11, color: C.gris, marginBottom: 16, lineHeight: 1.5 },
  sectionSubtitleBlanco: { fontSize: 11, color: '#ffffffaa', marginBottom: 16, lineHeight: 1.5 },
  body: { fontSize: 9, lineHeight: 1.6, marginBottom: 8, color: C.gris },
  bodyBlanco: { fontSize: 9, lineHeight: 1.6, marginBottom: 8, color: '#ffffffcc' },
  bold: { fontFamily: 'Helvetica-Bold' },
  italic: { fontStyle: 'italic' },
  oro: { color: C.oro },
  rojo: { color: C.rojo },
  verde: { color: C.verde },
  table: { marginBottom: 16 },
  tableHeader: { flexDirection: 'row', backgroundColor: C.negro, paddingVertical: 6, paddingHorizontal: 8 },
  tableHeaderNegro: { flexDirection: 'row', backgroundColor: '#ffffff15', paddingVertical: 6, paddingHorizontal: 8 },
  tableRow: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, borderBottomWidth: 0.5, borderBottomColor: '#00000010' },
  tableRowNegro: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, borderBottomWidth: 0.5, borderBottomColor: '#ffffff10' },
  tableRowAlt: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, backgroundColor: '#00000005', borderBottomWidth: 0.5, borderBottomColor: '#00000010' },
  tableRowHighlight: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, backgroundColor: '#c9a95915', borderBottomWidth: 0.5, borderBottomColor: '#c9a95930' },
  tableRowHighlightNegro: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, backgroundColor: '#c9a95920', borderBottomWidth: 0.5, borderBottomColor: '#c9a95940' },
  th: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.blanco, textTransform: 'uppercase', letterSpacing: 1 },
  thNegro: { fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.oro, textTransform: 'uppercase', letterSpacing: 1 },
  td: { fontSize: 8, color: C.negro },
  tdNegro: { fontSize: 8, color: '#ffffffdd' },
  tdBold: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: C.negro },
  tdOro: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: C.oro },
  kpiRow: { flexDirection: 'row', marginBottom: 16, gap: 12 },
  kpiBox: { flex: 1, backgroundColor: C.negro, padding: 14, alignItems: 'center' },
  kpiBoxCrema: { flex: 1, backgroundColor: C.crema, padding: 14, alignItems: 'center', borderWidth: 0.5, borderColor: '#00000015' },
  kpiValue: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: C.oro, marginBottom: 4 },
  kpiValueBlanco: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: C.blanco, marginBottom: 4 },
  kpiLabel: { fontSize: 7, color: '#ffffff88', textTransform: 'uppercase', letterSpacing: 2, textAlign: 'center' },
  kpiLabelNegro: { fontSize: 7, color: C.gris, textTransform: 'uppercase', letterSpacing: 2, textAlign: 'center' },
  callout: { backgroundColor: '#c9a95912', borderLeftWidth: 2, borderLeftColor: C.oro, padding: 12, marginBottom: 16 },
  calloutNegro: { backgroundColor: '#c9a95915', borderLeftWidth: 2, borderLeftColor: C.oro, padding: 12, marginBottom: 16 },
  calloutRojo: { backgroundColor: '#c9404012', borderLeftWidth: 2, borderLeftColor: C.rojo, padding: 12, marginBottom: 16 },
  calloutVerde: { backgroundColor: '#4a996012', borderLeftWidth: 2, borderLeftColor: C.verde, padding: 12, marginBottom: 16 },
  footer: { position: 'absolute', bottom: 20, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 7, color: '#ffffff55' },
  footerTextNegro: { fontSize: 7, color: '#00000044' },
  divider: { height: 0.5, backgroundColor: '#00000015', marginVertical: 12 },
  dividerBlanco: { height: 0.5, backgroundColor: '#ffffff20', marginVertical: 12 },
  badge: { paddingHorizontal: 6, paddingVertical: 2, fontSize: 7, fontFamily: 'Helvetica-Bold', color: C.blanco },
  smallNote: { fontSize: 7, color: C.grisMedio, lineHeight: 1.4, marginTop: 4 },
  smallNoteBlanco: { fontSize: 7, color: '#ffffff66', lineHeight: 1.4, marginTop: 4 },
});

// Helper
const Footer = ({ num, total, dark }) => (
  React.createElement(View, { style: s.footer },
    React.createElement(Text, { style: dark ? s.footerText : s.footerTextNegro }, 'SICI Intelligence'),
    React.createElement(Text, { style: dark ? s.footerText : s.footerTextNegro }, `${num} / ${total}`)
  )
);

// ═══════════════════════════════════════════
// REPORT 1: GIARDINO INDIVIDUAL
// ═══════════════════════════════════════════
const GiardinoReport = () => React.createElement(Document, {},
  // ─── Cover ───
  React.createElement(Page, { size: 'A4', style: s.pageCover },
    React.createElement(Text, { style: s.coverLabel }, 'INFORME DE INTELIGENCIA COMERCIAL'),
    React.createElement(Text, { style: s.coverTitle }, 'GIARDINO'),
    React.createElement(Text, { style: s.coverSubtitle }, 'Sirari — Mercado Ultra-Premium'),
    React.createElement(View, { style: s.coverLine }),
    React.createElement(Text, { style: s.coverMeta }, 'Elaborado con datos del Sistema SICI'),
    React.createElement(Text, { style: s.coverMeta }, '18 de febrero de 2026'),
    React.createElement(Text, { style: { ...s.coverMeta, marginTop: 20 } }, 'Precios en USD (TC oficial Bs 6.96)'),
    React.createElement(Text, { style: s.coverMeta }, 'Fuentes: Century 21 Bolivia, Remax Bolivia, Binance P2P'),
  ),

  // ─── P2: Resumen Ejecutivo ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'RESUMEN EJECUTIVO'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Giardino + Portfolio en contexto'),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '47+'),
        React.createElement(Text, { style: s.kpiLabel }, 'UNIDADES DISPONIBLES'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '1D+2D+3D'),
        React.createElement(Text, { style: s.kpiLabel }, 'TIPOLOGIAS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, 'Oct 2027'),
        React.createElement(Text, { style: s.kpiLabel }, 'ENTREGA'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, 'Sirari'),
        React.createElement(Text, { style: s.kpiLabel }, 'UBICACION'),
      ),
    ),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 16 } }, '$2,778-2,937'),
        React.createElement(Text, { style: s.kpiLabel }, '$/M2 (TC OFICIAL)'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '222'),
        React.createElement(Text, { style: s.kpiLabel }, 'MERCADO ACTIVAS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '40'),
        React.createElement(Text, { style: s.kpiLabel }, 'SIRARI ACTIVAS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '54+'),
        React.createElement(Text, { style: s.kpiLabel }, 'PORTFOLIO TOTAL'),
      ),
    ),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'El 1D es el producto estrella: unico segmento con absorcion en Sirari (9.5%).'),
      React.createElement(Text, { style: s.bodyBlanco }, '25 unidades desde $149K. MARE no tiene 1D — Giardino llena ese vacio. ROI estimado 5.2%.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '2D y 3D: mercado congelado en portales, requiere estrategia activa.'),
      React.createElement(Text, { style: s.bodyBlanco }, '0% absorcion en Sirari para 2D y 3D. Las 25 unidades en estos segmentos necesitan plan de pagos, renta garantizada o incentivos.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Giardino duplica la oferta de Sirari: 47 nuevas + 40 existentes.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Esto no es negativo si la torre genera demanda nueva, pero hay que ser consciente del impacto en velocidad de absorcion.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Portfolio combinado: MARE (hoy) + Giardino (Oct 2027) = cobertura completa.'),
      React.createElement(Text, { style: s.bodyBlanco }, '54+ unidades, tickets $119K-$373K, tipologias 1D a 3D. MARE entrega ya, Giardino cubre lo que MARE no tiene.'),
    ),
    React.createElement(Footer, { num: 2, total: 16, dark: true }),
  ),

  // ─── P3: Disclaimer ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'NOTA METODOLOGICA'),
    React.createElement(Text, { style: s.sectionTitle }, 'Sobre este informe'),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: s.body },
        'Los precios de Giardino provienen del PDF de disponibilidad (11 Feb 2026) y estan en dolares paralelo. Para comparar con el mercado (normalizado a TC oficial Bs 6.96), se convierten a USD oficial: precio x TC Binance (9.26) / 6.96 = x1.33. Todos los precios en este informe estan en USD (TC oficial) salvo donde se indique lo contrario.'
      ),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, 'Conversion aplicada:'),
      React.createElement(Text, { style: s.body }, 'Precio PDF $110,206 (paralelo) = $110,206 x 9.26 / 6.96 = $146,612 USD oficial'),
    ),
    React.createElement(Text, { style: s.body }, 'Datos de absorcion: ventana de 30 dias corridos desde el 18 de febrero de 2026. Se verificaron las 15 propiedades del backlog retroactivo (18-19 Ene) — 0 falsos positivos confirmados.'),
    React.createElement(Text, { style: s.body }, 'Zona analizada: Sirari — 40 unidades activas. Incluye propiedades de ambos portales (C21 + Remax) en las microzonas aledanhas al Hotel Los Tajibos y Av. San Martin.'),
    React.createElement(View, { style: s.divider }),
    React.createElement(Text, { style: s.sectionLabel }, 'GIARDINO EN NUMEROS'),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '47+'),
        React.createElement(Text, { style: s.kpiLabel }, 'UNIDADES DISPONIBLES'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '30'),
        React.createElement(Text, { style: s.kpiLabel }, 'PISOS / 2 TORRES'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, 'Oct 27'),
        React.createElement(Text, { style: s.kpiLabel }, 'ENTREGA'),
      ),
    ),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '15%'),
        React.createElement(Text, { style: s.kpiLabel }, 'RESERVA'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, 'Sirari'),
        React.createElement(Text, { style: s.kpiLabel }, 'UBICACION'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '1-3D'),
        React.createElement(Text, { style: s.kpiLabel }, 'TIPOLOGIAS'),
      ),
    ),
    React.createElement(Footer, { num: 3, total: 16 }),
  ),

  // ─── P4: Contexto Equipetrol — Panorama ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'CONTEXTO DE MERCADO'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Panorama general del mercado'),
    React.createElement(Text, { style: s.sectionSubtitleBlanco }, '222 propiedades de venta activas en 5 microzonas de Equipetrol. Datos limpios al 18 Feb 2026.'),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '222'),
        React.createElement(Text, { style: s.kpiLabel }, 'VENTA ACTIVAS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '48'),
        React.createElement(Text, { style: s.kpiLabel }, 'ABSORBIDAS 30D'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '17.8%'),
        React.createElement(Text, { style: s.kpiLabel }, 'TASA ABSORCION'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '4.6'),
        React.createElement(Text, { style: s.kpiLabel }, 'MESES INVENTARIO'),
      ),
    ),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '$2,071'),
        React.createElement(Text, { style: s.kpiLabel }, 'MEDIANA $/M2'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '$140K'),
        React.createElement(Text, { style: s.kpiLabel }, 'TICKET MEDIANO'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: s.kpiValue }, '95'),
        React.createElement(Text, { style: s.kpiLabel }, 'ALQUILERES'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 16 } }, '4.6-5.2%'),
        React.createElement(Text, { style: s.kpiLabel }, 'ROI BRUTO'),
      ),
    ),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(Text, { style: { fontSize: 12, color: C.blanco, fontFamily: 'Helvetica-Bold', marginBottom: 10 } }, 'Absorcion por tipologia — mercado completo'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'TIPOLOGIA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '12%' } }, 'ACTIVAS'),
        React.createElement(Text, { style: { ...s.thNegro, width: '14%' } }, 'ABSORB. 30D'),
        React.createElement(Text, { style: { ...s.thNegro, width: '12%' } }, 'TASA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '14%' } }, 'MESES INV.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, '$/M2 MED.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'TICKET MED.'),
      ),
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, 'Studio (0d)'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '28'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '9'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '24.3%'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '3.1'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$2,228'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$87K'),
      ),
      React.createElement(View, { style: s.tableRowHighlightNegro },
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '1 dormitorio'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '92'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '26'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '22.2%'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '3.5'),
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '$2,094'),
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '$106K'),
      ),
      React.createElement(View, { style: s.tableRowHighlightNegro },
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '2 dormitorios'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '82'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '9'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '9.9%'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '9.1'),
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '$2,005'),
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '$188K'),
      ),
      React.createElement(View, { style: s.tableRowHighlightNegro },
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '3 dormitorios'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '19'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '4'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '17.4%'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '4.8'),
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '$1,972'),
        React.createElement(Text, { style: { ...s.tdOro, width: '16%' } }, '$348K'),
      ),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: s.bodyBlanco }, 'Giardino compite en 3 de las 4 tipologias. El 1D (22.2%) y 3D (17.4%) tienen buena absorcion. El 2D (9.9%) es el mas lento y requiere estrategia diferenciada.'),
    ),
    React.createElement(Footer, { num: 4, total: 16, dark: true }),
  ),

  // ─── P5: Contexto Equipetrol — Absorcion por zona ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'CONTEXTO DE MERCADO (CONT.)'),
    React.createElement(Text, { style: s.sectionTitle }, 'Absorcion por microzona'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '16%' } }, 'ZONA'),
        React.createElement(Text, { style: { ...s.th, width: '12%' } }, 'ACTIVAS'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'ABSORB. 30D'),
        React.createElement(Text, { style: { ...s.th, width: '12%' } }, 'TASA'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'MESES INV.'),
        React.createElement(Text, { style: { ...s.th, width: '12%' } }, '$/M2'),
        React.createElement(Text, { style: { ...s.th, width: '20%' } }, 'PERFIL'),
      ),
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '16%' } }, 'Eq. Centro'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '99'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '28'),
        React.createElement(Text, { style: { ...s.tdBold, width: '12%' } }, '22.0%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '3.5'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$2,138'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, 'Motor'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '16%' } }, 'V. Brigida'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '36'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '12'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '12%', fontSize: 8 } }, '25.0%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '3.0'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$1,862'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, 'Emergente'),
      ),
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '16%' } }, 'Sirari'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '40'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '2'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '12%', fontSize: 8 } }, '4.8%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '20.0'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$2,118'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, 'Premium'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '16%' } }, 'Eq. Oeste'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '25'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '3'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '10.7%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '8.3'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$2,208'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, 'Mixto'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '16%' } }, 'Eq. Norte'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '22'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '3'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '12.0%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '7.3'),
        React.createElement(Text, { style: { ...s.td, width: '12%' } }, '$2,442'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, 'Financiero'),
      ),
    ),
    React.createElement(View, { style: s.divider }),
    React.createElement(Text, { style: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 10, color: C.negro } }, 'Cruce critico: Sirari x tipologias de Giardino'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '35%' } }, 'COMBINACION'),
        React.createElement(Text, { style: { ...s.th, width: '20%' } }, 'ACTIVAS'),
        React.createElement(Text, { style: { ...s.th, width: '22%' } }, 'ABSORB. 30D'),
        React.createElement(Text, { style: { ...s.th, width: '23%' } }, 'TASA'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '35%' } }, 'Sirari + 1 dorm'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '19'),
        React.createElement(Text, { style: { ...s.td, width: '22%' } }, '2'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '23%', fontSize: 8 } }, '9.5%'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '35%' } }, 'Sirari + 2 dorms'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '8'),
        React.createElement(Text, { style: { ...s.td, width: '22%' } }, '0'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '23%', fontSize: 8 } }, '0.0%'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.tdBold, width: '35%' } }, 'Sirari + 3 dorms'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '7'),
        React.createElement(Text, { style: { ...s.td, width: '22%' } }, '0'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '23%', fontSize: 8 } }, '0.0%'),
      ),
      React.createElement(View, { style: s.tableRowAlt },
        React.createElement(Text, { style: { ...s.td, width: '35%', ...s.italic } }, 'Eq. Centro + 1 dorm (ref.)'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '40'),
        React.createElement(Text, { style: { ...s.td, width: '22%' } }, '18'),
        React.createElement(Text, { style: { ...s.td, width: '23%' } }, '31.0%'),
      ),
      React.createElement(View, { style: s.tableRowAlt },
        React.createElement(Text, { style: { ...s.td, width: '35%', ...s.italic } }, 'V. Brigida + 2 dorms (ref.)'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '14'),
        React.createElement(Text, { style: { ...s.td, width: '22%' } }, '4'),
        React.createElement(Text, { style: { ...s.td, width: '23%' } }, '22.2%'),
      ),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: s.body }, 'Sirari 1D es el unico cruce con absorcion activa. Los compradores de 2D y 3D en Sirari compran directo con desarrolladoras — la baja absorcion en portales no refleja la demanda real, pero si exige una estrategia de venta proactiva.'),
    ),
    React.createElement(Footer, { num: 5, total: 16 }),
  ),

  // ─── P6: Inventario Giardino ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'INVENTARIO DISPONIBLE'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Giardino — Detalle por tipologia'),
    React.createElement(Text, { style: s.sectionSubtitleBlanco }, 'Precios convertidos a USD oficial (TC 6.96). Factor: precio paralelo x 1.33'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'TIPO'),
        React.createElement(Text, { style: { ...s.thNegro, width: '8%' } }, 'HAB'),
        React.createElement(Text, { style: { ...s.thNegro, width: '12%' } }, 'M2 INT.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'TORRE'),
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'DISP.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '22%' } }, 'RANGO $ OFIC.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '14%' } }, '$/M2 PAR.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '14%' } }, '$/M2 OFICIAL'),
      ),
      // 3D
      React.createElement(View, { style: s.tableRowHighlightNegro },
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '02'),
        React.createElement(Text, { style: { ...s.tdOro, width: '8%' } }, '3D'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '124'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, 'RESID.'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '7'),
        React.createElement(Text, { style: { ...s.tdOro, width: '22%' } }, '$365K-$387K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '$2,208'),
        React.createElement(Text, { style: { ...s.tdOro, width: '14%' } }, '$2,937'),
      ),
      // 2D Tipo 01
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '01'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '8%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '110.5'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, 'RESID.'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '3'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, '$325K-$415K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,204'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,931'),
      ),
      // 2D Tipo 03
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '03'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '8%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '95.8'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, 'RESID.'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '9'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, '$277K-$290K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,174'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,891'),
      ),
      // 2D Tipo 04
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '04'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '8%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '100'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, 'RESID.'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '6'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, '$290K-$301K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,185'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,906'),
      ),
      // 1D Tipo 05
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '05'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '8%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '52'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, 'VITA'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '10'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, '$146K-$156K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,119'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,818'),
      ),
      // 1D Tipo 06
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '06'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '8%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '52'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, 'VITA'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '7'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, '$145K-$154K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,106'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,801'),
      ),
      // 1D Tipo 07
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '07'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '8%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '52'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, 'VITA'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '5'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, '$145K-$152K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,088'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '$2,778'),
      ),
      // 1D Tipo 08
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '08'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '8%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '59'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, 'VITA'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '~3'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '22%' } }, 'parcial'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '~$1,900'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '14%' } }, '~$2,527'),
      ),
    ),
    React.createElement(Text, { style: s.smallNoteBlanco }, 'Pisos 26-30: "LA RISERVA" (reservados/vendidos). Los precios varian por piso y tipo de terraza.'),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, 'Resumen: ~25 unidades 1D + ~18 unidades 2D + 7 unidades 3D = 47+ unidades por colocar.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Precio promedio Giardino (USD oficial): 1D ~$149K | 2D ~$293K | 3D ~$373K'),
    ),
    React.createElement(Footer, { num: 6, total: 16, dark: true }),
  ),

  // ─── P7: Mercado Sirari ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'CONTEXTO DE MERCADO'),
    React.createElement(Text, { style: s.sectionTitle }, 'Sirari: mercado pequenho, premium, iliquido'),
    React.createElement(Text, { style: s.sectionSubtitle }, 'Solo 40 unidades activas en todo Sirari vs 222 en Equipetrol total. Giardino va a duplicar la oferta del barrio.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '15%' } }, 'TIPOLOGIA'),
        React.createElement(Text, { style: { ...s.th, width: '13%' } }, 'ACTIVAS'),
        React.createElement(Text, { style: { ...s.th, width: '15%' } }, 'ABSORB. 30D'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'TASA'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, '$/M2 PROM'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'AREA PROM'),
        React.createElement(Text, { style: { ...s.th, width: '15%' } }, 'GIARDINO DISP.'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '15%' } }, '1 Dorm'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '19'),
        React.createElement(Text, { style: { ...s.td, width: '15%' } }, '2'),
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '9.5%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$2,098'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '58 m2'),
        React.createElement(Text, { style: { ...s.tdOro, width: '15%' } }, '~25 uds'),
      ),
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '15%' } }, '2 Dorms'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '8'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '15%', fontSize: 8 } }, '0'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '14%', fontSize: 8 } }, '0.0%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$2,035'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '113 m2'),
        React.createElement(Text, { style: { ...s.tdOro, width: '15%' } }, '~18 uds'),
      ),
      React.createElement(View, { style: s.tableRowHighlight },
        React.createElement(Text, { style: { ...s.tdBold, width: '15%' } }, '3 Dorms'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '7'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '15%', fontSize: 8 } }, '0'),
        React.createElement(Text, { style: { ...s.rojo, ...s.bold, width: '14%', fontSize: 8 } }, '0.0%'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$2,201'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '230 m2'),
        React.createElement(Text, { style: { ...s.tdOro, width: '15%' } }, '7 uds'),
      ),
    ),
    React.createElement(View, { style: s.calloutRojo },
      React.createElement(Text, { style: { ...s.body, ...s.bold, color: C.rojo } }, 'Alerta de liquidez:'),
      React.createElement(Text, { style: s.body }, 'En los ultimos 30 dias, CERO unidades de 2 y 3 dormitorios se absorbieron en Sirari. Giardino planea colocar 25 unidades en estos segmentos. Esto implica un horizonte de venta potencialmente largo sin ajuste de estrategia.'),
    ),
    React.createElement(View, { style: s.calloutVerde },
      React.createElement(Text, { style: { ...s.body, ...s.bold, color: C.verde } }, 'Oportunidad en 1 dormitorio:'),
      React.createElement(Text, { style: s.body }, 'El segmento de 1D es el unico con absorcion activa (9.5%, 2 unidades en 30 dias). Las 25 unidades 1D de Giardino tienen mercado demostrado, aunque la tasa de absorcion sugiere ~10 meses para colocar todo el inventario.'),
    ),
    React.createElement(Footer, { num: 7, total: 16 }),
  ),

  // ─── P8: Giardino vs Mercado (percentiles) ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'POSICIONAMIENTO'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Giardino vs mercado Equipetrol'),
    React.createElement(Text, { style: s.sectionSubtitleBlanco }, 'Precio por m2 y ticket total comparados con percentiles 25, 50 (mediana) y 75 del mercado completo (222 unidades activas, todas las zonas).'),

    React.createElement(View, { style: { ...s.calloutNegro, marginBottom: 12 } },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'PRECIO POR M2 (USD oficial)'),
    ),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'TIP.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'P25'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'MEDIANA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'P75'),
        React.createElement(Text, { style: { ...s.thNegro, width: '18%' } }, 'GIARDINO'),
        React.createElement(Text, { style: { ...s.thNegro, width: '18%' } }, 'POSICION'),
      ),
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$1,727'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$2,003'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$2,314'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '$2,794'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '> P75'),
      ),
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$1,752'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$1,918'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$2,252'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '$2,927'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '> P75'),
      ),
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '3D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$1,459'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$1,871'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$2,258'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '$2,994'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '> P75'),
      ),
    ),

    React.createElement(View, { style: { ...s.calloutNegro, marginTop: 16, marginBottom: 12 } },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'TICKET TOTAL (USD oficial)'),
    ),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'TIP.'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'P25'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'MEDIANA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '16%' } }, 'P75'),
        React.createElement(Text, { style: { ...s.thNegro, width: '18%' } }, 'GIARDINO'),
        React.createElement(Text, { style: { ...s.thNegro, width: '18%' } }, 'POSICION'),
      ),
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$85K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$101K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$132K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '$149K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '> P75'),
      ),
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$145K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$181K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$231K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '$293K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '> P75'),
      ),
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '3D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$235K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$289K'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '16%' } }, '$429K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, '$373K'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, 'P50-P75'),
      ),
    ),

    React.createElement(View, { style: { ...s.calloutNegro, marginTop: 16 } },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, 'Lectura rapida:'),
      React.createElement(Text, { style: s.bodyBlanco }, 'En $/m2, Giardino esta POR ENCIMA del P75 en las 3 tipologias — es un producto premium. En ticket total, 1D y 2D tambien superan el P75, pero 3D queda entre mediana y P75 porque las areas son mas compactas que el promedio del segmento.'),
      React.createElement(Text, { style: { ...s.bodyBlanco, marginTop: 4 } }, 'Mercado = 222 unidades activas en todo Equipetrol (C21 + Remax), filtros de calidad aplicados. Giardino = precios PDF convertidos a USD oficial (x1.33).'),
    ),
    React.createElement(Footer, { num: 8, total: 16, dark: true }),
  ),

  // ─── P9: Competidores Premium Sirari ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'COMPETENCIA DIRECTA'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Proyectos premium en Sirari (>$2,000/m2)'),
    React.createElement(Text, { style: s.sectionSubtitleBlanco }, '26 propiedades activas por encima de $2,000/m2 en todo Sirari. Giardino compite en un nicho premium con mas competencia de la esperada.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '30%' } }, 'PROYECTO'),
        React.createElement(Text, { style: { ...s.thNegro, width: '10%' } }, 'HAB'),
        React.createElement(Text, { style: { ...s.thNegro, width: '12%' } }, 'AREA'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, '$/M2'),
        React.createElement(Text, { style: { ...s.thNegro, width: '18%' } }, 'ESTADO'),
        React.createElement(Text, { style: { ...s.thNegro, width: '15%' } }, 'POSICION'),
      ),
      // MARE 1D reseller
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'MARE (reseller)'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '70 m2'),
        React.createElement(Text, { style: { ...s.tdOro, width: '15%' } }, '$3,535'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'Preventa'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Tope mercado'),
      ),
      // Sirari Palm 2D
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'Sirari Palm'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '66 m2'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,695'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'Ent. inmediata'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Competidor'),
      ),
      // Las Dalias 1D (agrupado)
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'Las Dalias (6 uds)'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '46-80'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,002-2,558'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'Preventa'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Competidor'),
      ),
      // La Riviera 3D
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'La Riviera'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '3D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '204 m2'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,536'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'No espec.'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Competidor'),
      ),
      // MARE studio
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'MARE (studio)'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '0D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '43 m2'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,513'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'No espec.'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Hermano'),
      ),
      // La Riviera 4D
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'La Riviera'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '4D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '303 m2'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,475'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'Ent. inmediata'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Competidor'),
      ),
      // Sirari Palm 1D
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'Sirari Palm'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '1D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '48 m2'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,445'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'Ent. inmediata'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Competidor'),
      ),
      // ITAJU 3D
      React.createElement(View, { style: s.tableRowHighlightNegro },
        React.createElement(Text, { style: { ...s.tdOro, width: '30%' } }, 'ITAJU'),
        React.createElement(Text, { style: { ...s.tdOro, width: '10%' } }, '3D'),
        React.createElement(Text, { style: { ...s.tdOro, width: '12%' } }, '211-330'),
        React.createElement(Text, { style: { ...s.tdOro, width: '15%' } }, '$2,258-2,320'),
        React.createElement(Text, { style: { ...s.tdOro, width: '18%' } }, 'Ent. inmediata'),
        React.createElement(Text, { style: { ...s.tdOro, width: '15%' } }, 'Benchmark 3D'),
      ),
      // MARE 2D reseller
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'MARE (reseller)'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '142 m2'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,253'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'Preventa'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Hermano'),
      ),
      // OMNIA PRIME
      React.createElement(View, { style: s.tableRowNegro },
        React.createElement(Text, { style: { ...s.tdNegro, width: '30%' } }, 'OMNIA PRIME'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '10%' } }, '2D'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '12%' } }, '88 m2'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, '$2,031'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '18%' } }, 'No espec.'),
        React.createElement(Text, { style: { ...s.tdNegro, width: '15%' } }, 'Competidor'),
      ),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, 'Giardino (USD oficial): 1D ~$2,794/m2 | 2D ~$2,927/m2 | 3D ~$2,994/m2'),
      React.createElement(Text, { style: s.bodyBlanco }, 'En USD oficial, Giardino se posiciona POR ENCIMA de la mayoria de competidores: supera a OMNIA PRIME ($2,031), Sirari Palm ($2,445-2,695) y ITAJU ($2,258-2,320). Solo queda por debajo de MARE reseller ($3,535).'),
    ),
    React.createElement(Footer, { num: 9, total: 16, dark: true }),
  ),

  // ─── P9: Renta y ROI ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'RENTA E INVERSION'),
    React.createElement(Text, { style: s.sectionTitle }, 'ROI Potencial: Giardino para inversores'),
    React.createElement(Text, { style: s.sectionSubtitle }, 'Sirari tiene rentas mas altas que el promedio, con muestra pequenha (9 alquileres activos).'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '16%' } }, 'TIPOLOGIA'),
        React.createElement(Text, { style: { ...s.th, width: '16%' } }, 'RENTA/MES'),
        React.createElement(Text, { style: { ...s.th, width: '20%' } }, 'TICKET GIARDINO'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'ROI BRUTO'),
        React.createElement(Text, { style: { ...s.th, width: '16%' } }, 'ANOS RETORNO'),
        React.createElement(Text, { style: { ...s.th, width: '18%' } }, 'VS EQUIPETROL'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, '1 Dorm'),
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, '$647/mes'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '$149K'),
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '5.21%'),
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, '19.2 anhos'),
        React.createElement(Text, { style: { ...s.verde, ...s.bold, width: '18%', fontSize: 8 } }, 'Similar (6.78%)'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, '2 Dorms'),
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, '$1,124/mes'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '$293K'),
        React.createElement(Text, { style: { ...s.tdBold, width: '14%' } }, '4.60%'),
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, '21.7 anhos'),
        React.createElement(Text, { style: { ...s.td, width: '18%', fontSize: 8 } }, 'Similar (6.37%)'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, '3 Dorms'),
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, 'Sin datos'),
        React.createElement(Text, { style: { ...s.td, width: '20%' } }, '$373K'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, 'N/D'),
        React.createElement(Text, { style: { ...s.td, width: '16%' } }, 'N/D'),
        React.createElement(Text, { style: { ...s.td, width: '18%', fontSize: 8 } }, 'Equipetrol: 5.61%'),
      ),
    ),
    React.createElement(Text, { style: s.smallNote }, 'ROI bruto = (renta mensual x 12) / ticket Giardino en USD oficial. No descuenta vacancia, mantenimiento ni comisiones. Renta de Sirari basada en muestra de 9 alquileres activos (C21 + Remax). 1D: 2 unidades, mediana $546 Equipetrol. 2D: 3 unidades, mediana $1,307.'),

    React.createElement(View, { style: s.divider }),
    React.createElement(Text, { style: { ...s.sectionTitle, fontSize: 12, marginBottom: 4 } }, 'Yield estimado: 1 dormitorio ($149K)'),
    React.createElement(Text, { style: { ...s.body, fontStyle: 'italic', marginBottom: 6, fontSize: 8 } }, 'Mediana Equipetrol 1D: $546/mes. Sirari no tiene muestra suficiente en 1D — se usa Equipetrol como base.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '24%' } }, 'ESCENARIO'),
        React.createElement(Text, { style: { ...s.th, width: '18%' } }, 'RENTA/MES'),
        React.createElement(Text, { style: { ...s.th, width: '18%' } }, 'RENTA/ANO'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'TICKET'),
        React.createElement(Text, { style: { ...s.th, width: '13%' } }, 'YIELD'),
        React.createElement(Text, { style: { ...s.th, width: '13%' } }, 'ANOS'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '24%' } }, 'Conservador'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$546'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$6,552'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$149K'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '4.4%'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '22.7'),
      ),
      React.createElement(View, { style: { ...s.tableRow, backgroundColor: '#c9a95920' } },
        React.createElement(Text, { style: { ...s.tdBold, width: '24%', color: C.oro } }, 'Moderado (+30%)'),
        React.createElement(Text, { style: { ...s.tdBold, width: '18%', color: C.oro } }, '$710'),
        React.createElement(Text, { style: { ...s.tdBold, width: '18%', color: C.oro } }, '$8,520'),
        React.createElement(Text, { style: { ...s.tdBold, width: '14%', color: C.oro } }, '$149K'),
        React.createElement(Text, { style: { ...s.tdBold, width: '13%', color: C.oro } }, '5.7%'),
        React.createElement(Text, { style: { ...s.tdBold, width: '13%', color: C.oro } }, '17.5'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '24%' } }, 'Optimista (+57%)'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$857'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$10,284'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$149K'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '6.9%'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '14.5'),
      ),
    ),

    React.createElement(View, { style: { ...s.divider, marginTop: 8 } }),
    React.createElement(Text, { style: { ...s.sectionTitle, fontSize: 12, marginBottom: 4 } }, 'Yield estimado: 2 dormitorios ($293K)'),
    React.createElement(Text, { style: { ...s.body, fontStyle: 'italic', marginBottom: 6, fontSize: 8 } }, 'Mediana Equipetrol 2D: $862/mes. Sirari real: $1,124/mes (+30% vs Equipetrol). MARE studio renta +6%, 1D +57% vs mercado.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '24%' } }, 'ESCENARIO'),
        React.createElement(Text, { style: { ...s.th, width: '18%' } }, 'RENTA/MES'),
        React.createElement(Text, { style: { ...s.th, width: '18%' } }, 'RENTA/ANO'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'TICKET'),
        React.createElement(Text, { style: { ...s.th, width: '13%' } }, 'YIELD'),
        React.createElement(Text, { style: { ...s.th, width: '13%' } }, 'ANOS'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '24%' } }, 'Conservador'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$862'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$10,344'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$293K'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '3.5%'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '28.3'),
      ),
      React.createElement(View, { style: { ...s.tableRow, backgroundColor: '#c9a95920' } },
        React.createElement(Text, { style: { ...s.tdBold, width: '24%', color: C.oro } }, 'Moderado (+30%)'),
        React.createElement(Text, { style: { ...s.tdBold, width: '18%', color: C.oro } }, '$1,124'),
        React.createElement(Text, { style: { ...s.tdBold, width: '18%', color: C.oro } }, '$13,488'),
        React.createElement(Text, { style: { ...s.tdBold, width: '14%', color: C.oro } }, '$293K'),
        React.createElement(Text, { style: { ...s.tdBold, width: '13%', color: C.oro } }, '4.6%'),
        React.createElement(Text, { style: { ...s.tdBold, width: '13%', color: C.oro } }, '21.7'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '24%' } }, 'Optimista (+57%)'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$1,353'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$16,236'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$293K'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '5.5%'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '18.0'),
      ),
    ),

    React.createElement(View, { style: { ...s.divider, marginTop: 8 } }),
    React.createElement(Text, { style: { ...s.sectionTitle, fontSize: 12, marginBottom: 4 } }, 'Yield estimado: 3 dormitorios ($373K)'),
    React.createElement(Text, { style: { ...s.body, fontStyle: 'italic', marginBottom: 6, fontSize: 8 } }, 'Mediana Equipetrol 3D: $1,652/mes (5 alquileres). Sin datos Sirari 3D — se usa Equipetrol como base.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '24%' } }, 'ESCENARIO'),
        React.createElement(Text, { style: { ...s.th, width: '18%' } }, 'RENTA/MES'),
        React.createElement(Text, { style: { ...s.th, width: '18%' } }, 'RENTA/ANO'),
        React.createElement(Text, { style: { ...s.th, width: '14%' } }, 'TICKET'),
        React.createElement(Text, { style: { ...s.th, width: '13%' } }, 'YIELD'),
        React.createElement(Text, { style: { ...s.th, width: '13%' } }, 'ANOS'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '24%' } }, 'Conservador'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$1,652'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$19,824'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$373K'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '5.3%'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '18.8'),
      ),
      React.createElement(View, { style: { ...s.tableRow, backgroundColor: '#c9a95920' } },
        React.createElement(Text, { style: { ...s.tdBold, width: '24%', color: C.oro } }, 'Moderado (+30%)'),
        React.createElement(Text, { style: { ...s.tdBold, width: '18%', color: C.oro } }, '$2,148'),
        React.createElement(Text, { style: { ...s.tdBold, width: '18%', color: C.oro } }, '$25,776'),
        React.createElement(Text, { style: { ...s.tdBold, width: '14%', color: C.oro } }, '$373K'),
        React.createElement(Text, { style: { ...s.tdBold, width: '13%', color: C.oro } }, '6.9%'),
        React.createElement(Text, { style: { ...s.tdBold, width: '13%', color: C.oro } }, '14.5'),
      ),
      React.createElement(View, { style: s.tableRow },
        React.createElement(Text, { style: { ...s.td, width: '24%' } }, 'Optimista (+57%)'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$2,594'),
        React.createElement(Text, { style: { ...s.td, width: '18%' } }, '$31,128'),
        React.createElement(Text, { style: { ...s.td, width: '14%' } }, '$373K'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '8.3%'),
        React.createElement(Text, { style: { ...s.td, width: '13%' } }, '12.0'),
      ),
    ),

    React.createElement(Text, { style: { ...s.smallNote, marginTop: 8 } }, 'Conservador = mediana Equipetrol. Moderado = +30% (premium Sirari observado en 2D). Optimista = +57% (premium MARE observado en 1D). Yield bruto, no descuenta vacancia ni comisiones.'),
    React.createElement(Footer, { num: 10, total: 16 }),
  ),

  // ─── P10b: Preventa vs Entrega ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'PREVENTA VS ENTREGA INMEDIATA'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'El desafio de Giardino: preventa Oct 2027'),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: s.bodyBlanco }, 'En Sirari, las unicas propiedades premium que se absorbieron fueron 2 unidades de 1D — ambas de preventa ($1,952/m2 promedio). En 2D y 3D, la absorcion es CERO tanto en preventa como en entrega inmediata.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, 'Dato critico:'),
      React.createElement(Text, { style: s.bodyBlanco }, 'ITAJU (3D, entrega inmediata, $2,258/m2) tiene 5 unidades activas sin absorcion en 30 dias. Giardino compite a precio SUPERIOR ($2,994/m2 oficial) y SIN el producto terminado. El comprador de 3D en Sirari prefiere ver antes de comprar.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Ventaja de preventa para el inversor:'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Si Giardino renta a nivel moderado (+30% premium Sirari) desde Oct 2027, en 24 meses el inversor de 1D acumula ~$17K en renta. Costo efectivo: $149K - $17K = $132K, equivalente al P75 del mercado. El entry point real baja con el tiempo.'),
    ),
    React.createElement(View, { style: { ...s.calloutNegro, borderLeftColor: C.oro, borderLeftWidth: 3 } },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Resumen yield por tipologia (escenario moderado):'),
      React.createElement(Text, { style: s.bodyBlanco }, '1D: $710/mes → 5.7% yield → 17.5 anhos retorno'),
      React.createElement(Text, { style: s.bodyBlanco }, '2D: $1,124/mes → 4.6% yield → 21.7 anhos retorno'),
      React.createElement(Text, { style: s.bodyBlanco }, '3D: $2,148/mes → 6.9% yield → 14.5 anhos retorno'),
      React.createElement(Text, { style: { ...s.bodyBlanco, marginTop: 6, fontStyle: 'italic' } }, 'El 3D tiene el mejor yield porque el ticket ($373K) esta entre P50-P75 mientras la renta de 3D es proporcionalmente alta.'),
    ),
    React.createElement(Footer, { num: 11, total: 16, dark: true }),
  ),

  // ─── P10: Conclusiones Giardino ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'CONCLUSIONES'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Giardino: oportunidad con gestion de riesgo'),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, '1. El 1D es su producto estrella.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Unico segmento con absorcion demostrada en Sirari (9.5%). 25 unidades a ~$149K es un ticket accesible para inversores. El ROI de 5.21% es moderado pero con renta premium Sirari. Recomendacion: priorizar la venta de 1D para generar flujo de caja.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, '2. El 2D requiere estrategia diferenciada.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Con 0% de absorcion en Sirari y 18 unidades por colocar, no se puede depender del mercado organico. Opciones: (a) Plan de pagos agresivo, (b) Bundle parqueo+baulera incluido, (c) Descuento por pisos bajos, (d) Campanh de renta garantizada para inversores.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, '3. El 3D compite contra producto terminado.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'ITAJU ofrece 3D entrega inmediata a $2,258/m2 — Giardino esta POR ENCIMA a $2,994/m2 y sin producto terminado. Para un comprador de $373K+ preventa Oct 2027 vs $477K entrega HOY en ITAJU, Giardino necesita un diferenciador fuerte (diseno, amenidades, "La Riserva" como aspiracional).'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold } }, '4. Giardino va a DUPLICAR la oferta de Sirari.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Hoy hay 40 unidades activas en todo Sirari. Giardino agrega 47+. Esto no es necesariamente negativo si la torre trae demanda nueva por la calidad del producto, pero hay que ser consciente del impacto en la velocidad de absorcion del barrio.'),
    ),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro, fontSize: 11 } }, 'Veredicto: Proyecto viable con pricing correcto. El riesgo no es el precio sino la liquidez de Sirari. La clave esta en generar demanda activa, no esperar compradores organicos.'),
    React.createElement(Footer, { num: 12, total: 16, dark: true }),
  ),

  // ─── P11: PORTFOLIO COMBINADO - Cover ───
  React.createElement(Page, { size: 'A4', style: s.pageCover },
    React.createElement(Text, { style: s.coverLabel }, 'ANALISIS DE PORTFOLIO'),
    React.createElement(Text, { style: { ...s.coverTitle, fontSize: 28 } }, 'MARE + GIARDINO'),
    React.createElement(Text, { style: s.coverSubtitle }, 'Dos proyectos, un barrio, una estrategia'),
    React.createElement(View, { style: s.coverLine }),
    React.createElement(Text, { style: s.coverMeta }, 'Sirari — MARE + Giardino'),
    React.createElement(Text, { style: s.coverMeta }, '18 de febrero de 2026'),
  ),

  // ─── P12: Portfolio en contexto Equipetrol ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'PORTFOLIO EN CONTEXTO'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, '54 unidades en un mercado de 222'),
    React.createElement(View, { style: s.kpiRow },
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 18 } }, '24%'),
        React.createElement(Text, { style: s.kpiLabel }, 'DEL INVENTARIO SIRARI SERA PORTFOLIO'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 14 } }, '$119K-$373K'),
        React.createElement(Text, { style: s.kpiLabel }, 'RANGO TICKETS'),
      ),
      React.createElement(View, { style: s.kpiBox },
        React.createElement(Text, { style: { ...s.kpiValue, fontSize: 18 } }, '1D a 3D'),
        React.createElement(Text, { style: s.kpiLabel }, 'COBERTURA'),
      ),
    ),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(Text, { style: { fontSize: 12, color: C.blanco, fontFamily: 'Helvetica-Bold', marginBottom: 10 } }, 'Posicion competitiva del portfolio'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeaderNegro },
        React.createElement(Text, { style: { ...s.thNegro, width: '22%' } }, 'DIMENSION'),
        React.createElement(Text, { style: { ...s.thNegro, width: '24%' } }, 'MARE (7 UDS)'),
        React.createElement(Text, { style: { ...s.thNegro, width: '28%' } }, 'GIARDINO (47 UDS)'),
        React.createElement(Text, { style: { ...s.thNegro, width: '26%' } }, 'MERCADO TOTAL (222)'),
      ),
      ...[
        ['Tipologias', 'Solo 2D', '1D, 2D, 3D', '0D a 4D'],
        ['$/m2 (USD oficial)', '$2,167-2,263', '$2,778-2,937', '$1,345-2,979'],
        ['Ticket', '$119K-302K', '$149K-$373K', '$73K-764K'],
        ['Zona', 'Sirari', 'Sirari', '5 microzonas'],
        ['Entrega', 'Inmediata', 'Oct 2027', 'Mixto'],
        ['% del inventario', '3.2% (7/222)', '— (no en portales aun)', '100%'],
      ].map(([dim, mare, giardino, mercado], i) =>
        React.createElement(View, { key: i, style: i % 2 === 0 ? s.tableRowNegro : s.tableRowHighlightNegro },
          React.createElement(Text, { style: { ...s.tdOro, width: '22%' } }, dim),
          React.createElement(Text, { style: { ...s.tdNegro, width: '24%' } }, mare),
          React.createElement(Text, { style: { ...s.tdNegro, width: '28%' } }, giardino),
          React.createElement(Text, { style: { ...s.tdNegro, width: '26%' } }, mercado),
        )
      ),
    ),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'Concentracion geografica = riesgo pero tambien oportunidad.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Todo el portfolio esta en Sirari (40 activas hoy + 47 Giardino = ~87 unidades futuras). No hay diversificacion geografica, pero la concentracion permite al broker ser EL experto de Sirari.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'ROI Sirari vs mercado Equipetrol:'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Sirari 2D: $1,124/mes renta, 6.6% ROI. Promedio Equipetrol 2D: $862/mes, 5.5% ROI. Sirari renta 30% mas que el promedio — el argumento de inversion para ambos proyectos.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, 'El timing es la clave del portfolio.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'MARE entrega HOY — renta desde dia 1 para inversores. Giardino entrega Oct 2027 — preventa con apreciacion de capital. Juntos cubren al inversor que quiere retorno inmediato Y al que quiere entry point mas bajo.'),
    ),
    React.createElement(Footer, { num: 13, total: 16, dark: true }),
  ),

  // ─── P13: Comparativo Portfolio ───
  React.createElement(Page, { size: 'A4', style: s.pageCrema },
    React.createElement(Text, { style: s.sectionLabel }, 'PORTFOLIO COMBINADO'),
    React.createElement(Text, { style: s.sectionTitle }, 'MARE vs Giardino: mismo barrio, distinto timing'),
    React.createElement(Text, { style: s.sectionSubtitle }, 'Ambos proyectos estan en Sirari — comparten el mismo micro-mercado de 40 unidades activas. La diferenciacion no es geografica sino temporal y de producto.'),
    React.createElement(View, { style: s.table },
      React.createElement(View, { style: s.tableHeader },
        React.createElement(Text, { style: { ...s.th, width: '25%' } }, 'DIMENSION'),
        React.createElement(Text, { style: { ...s.th, width: '37%' } }, 'MARE (SIRARI)'),
        React.createElement(Text, { style: { ...s.th, width: '38%' } }, 'GIARDINO (SIRARI)'),
      ),
      ...[
        ['Zona', 'Sirari — vecinos', 'Sirari — vecinos'],
        ['Entrega', 'Ent. inmediata / prox.', 'Oct 2027 (preventa)'],
        ['Tipologias', 'Solo 2D (7 uds)', '1D, 2D, 3D (47+ uds)'],
        ['Rango m2', '73-137 m2', '52-124 m2'],
        ['$/m2 (USD oficial)', '$2,167-2,263', '$2,778-2,937'],
        ['Ticket entrada', '$119K (73m2 2D)', '$149K (52m2 1D)'],
        ['Absorcion zona 2D', '0.0% (critico)', '0.0% (comparten cifra)'],
        ['Absorcion zona 1D', 'No aplica (no tiene)', '9.5% (unico con demanda)'],
        ['Amenidades', '19 (top del segmento)', '30 pisos, koi pond, La Riserva'],
        ['Riesgo principal', '0% absorcion 2D en Sirari', 'Liquidez + preventa larga'],
        ['Ventaja clave', 'Entrega inmediata = renta dia 1', 'Cubre 1D y 3D que MARE no tiene'],
      ].map(([dim, mare, giardino], i) =>
        React.createElement(View, { key: i, style: i % 2 === 0 ? s.tableRow : s.tableRowAlt },
          React.createElement(Text, { style: { ...s.tdBold, width: '25%' } }, dim),
          React.createElement(Text, { style: { ...s.td, width: '37%' } }, mare),
          React.createElement(Text, { style: { ...s.td, width: '38%' } }, giardino),
        )
      ),
    ),
    React.createElement(View, { style: s.calloutRojo },
      React.createElement(Text, { style: { ...s.body, ...s.bold, color: C.rojo } }, 'Concentracion de riesgo:'),
      React.createElement(Text, { style: s.body }, 'Ambos proyectos compiten en el MISMO micro-mercado de Sirari (40 unidades activas, 0% absorcion en 2D/3D). No hay diversificacion geografica. El exito depende de generar demanda nueva en un barrio con liquidez limitada en portales.'),
    ),
    React.createElement(View, { style: s.callout },
      React.createElement(Text, { style: { ...s.body, ...s.bold } }, 'Complementariedad temporal:'),
      React.createElement(Text, { style: s.body }, 'MARE entrega llaves HOY (solo 2D, 7 uds) — renta desde el dia 1. Giardino entrega Oct 2027 pero cubre 1D y 3D que MARE no tiene. El broker puede capturar TODO el espectro de comprador: desde inversor de 1D ($149K) hasta end-user de 3D ($373K).'),
    ),
    React.createElement(Footer, { num: 14, total: 16 }),
  ),

  // ─── P14: Estrategia Portfolio ───
  React.createElement(Page, { size: 'A4', style: s.pageNegro },
    React.createElement(Text, { style: s.sectionLabel }, 'ESTRATEGIA DE PORTFOLIO'),
    React.createElement(Text, { style: s.sectionTitleBlanco }, 'Recomendaciones accionables'),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '1. MARE primero: 2D entrega inmediata'),
      React.createElement(Text, { style: s.bodyBlanco }, 'MARE tiene 7 unidades de 2D listas para entregar. En un mercado con 0% de absorcion en 2D, la entrega inmediata es la unica arma diferencial real: el comprador puede ver, tocar y alquilar desde el dia 1.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Priorizar MARE 2D sobre Giardino 2D porque el comprador de 2D preventa Oct 2027 es mas dificil de cerrar.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '2. GIARDINO 1D: el producto mas liquido del portfolio'),
      React.createElement(Text, { style: s.bodyBlanco }, 'MARE no tiene 1D. Giardino si: 25 unidades desde $149K. El 1D es el UNICO segmento con absorcion demostrada en Sirari (9.5%). Giardino llena ese hueco.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Comprador que no califica para 2D MARE ($119K+) → Giardino 1D ($149K). No se pierde la venta.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '3. COMPLEMENTARIEDAD real del portfolio'),
      React.createElement(Text, { style: s.bodyBlanco }, 'MARE: solo 2D, entrega inmediata, 7 unidades, $2,167-2,263/m2.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Giardino: 1D + 2D + 3D, preventa Oct 2027, 47+ unidades, $2,778-2,937/m2.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Juntos cubren: todo el rango de tipologias (1D a 3D) + todo el rango temporal (hoy a Oct 2027) + tickets desde $119K hasta $373K.'),
    ),
    React.createElement(View, { style: s.calloutNegro },
      React.createElement(Text, { style: { ...s.bodyBlanco, ...s.bold, ...s.oro } }, '4. MONITOREO con datos SICI'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Snapshots diarios de absorcion, precios y ROI en Sirari. Reportes mensuales mostrando: inventario competidor, cambios de precio, absorcion real. El broker se convierte en asesor estrategico.'),
      React.createElement(Text, { style: s.bodyBlanco }, 'Dato clave: cuando la absorcion de 2D en Sirari pase de 0%, priorizar las 7 MARE restantes (entrega inmediata) antes que Giardino 2D (preventa).'),
    ),
    React.createElement(View, { style: s.dividerBlanco }),
    React.createElement(View, { style: { flexDirection: 'row', gap: 12 } },
      React.createElement(View, { style: { ...s.kpiBoxCrema, flex: 1 } },
        React.createElement(Text, { style: { ...s.kpiValueBlanco, color: C.oro, fontSize: 18 } }, '54+ uds'),
        React.createElement(Text, { style: { ...s.kpiLabelNegro, color: '#ffffffaa' } }, '7 MARE + 47 GIARDINO'),
      ),
      React.createElement(View, { style: { ...s.kpiBoxCrema, flex: 1 } },
        React.createElement(Text, { style: { ...s.kpiValueBlanco, color: C.oro, fontSize: 18 } }, 'Sirari'),
        React.createElement(Text, { style: { ...s.kpiLabelNegro, color: '#ffffffaa' } }, 'CONCENTRACION EN ZONA PREMIUM'),
      ),
      React.createElement(View, { style: { ...s.kpiBoxCrema, flex: 1 } },
        React.createElement(Text, { style: { ...s.kpiValueBlanco, color: C.oro, fontSize: 18 } }, '0-3D'),
        React.createElement(Text, { style: { ...s.kpiLabelNegro, color: '#ffffffaa' } }, 'COBERTURA COMPLETA'),
      ),
    ),
    React.createElement(Footer, { num: 15, total: 16, dark: true }),
  ),
);

// ─── Generate ───
async function generate() {
  const outputDir = path.join(__dirname, '..', 'docs', 'reports');
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const doc = React.createElement(GiardinoReport);
  const outputPath = path.join(outputDir, 'INFORME_GIARDINO_PORTFOLIO_2026-02-18_v3.pdf');

  console.log('Generating Giardino + Portfolio report...');
  await renderToFile(doc, outputPath);
  console.log(`PDF generated: ${outputPath}`);

  const stats = fs.statSync(outputPath);
  console.log(`Size: ${(stats.size / 1024).toFixed(1)} KB`);
}

generate().catch(console.error);
